# Generated by Django 3.0.6 on 2020-06-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField(max_length=200, verbose_name='Título')),
                ('Subtitle', models.TextField(max_length=200, verbose_name='Subtítulo')),
                ('Content', models.TextField(verbose_name='Contenido')),
                ('Image', models.ImageField(upload_to='services')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
